#!/usr/bin/env python3
"""
Interactive wizard — collects credentials and sign-in settings,
validates them against Azure Resource Graph, then writes .env.
Run this to create or update the configuration.
"""

import getpass
import os
import re
import secrets
import sys

GUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    re.IGNORECASE,
)
ENV_PATH = os.path.join(os.path.dirname(__file__), ".env")

GREEN  = "\033[92m"
RED    = "\033[91m"
YELLOW = "\033[93m"
RESET  = "\033[0m"


def ok(msg):   print(f"{GREEN}✓ {msg}{RESET}")
def err(msg):  print(f"{RED}✗ {msg}{RESET}")
def warn(msg): print(f"{YELLOW}⚠ {msg}{RESET}")


# ── .env I/O ─────────────────────────────────────────────────────────────────

def load_env(path: str) -> dict:
    """Parse existing .env into a plain dict (comment lines and blanks ignored)."""
    if not os.path.exists(path):
        return {}
    result = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            key, _, val = line.partition("=")
            result[key.strip()] = val.strip()
    return result


def write_env(values: dict):
    lines = ["# WTS Azure Cloud Manager — generated by setup_env.py"]
    for key, val in values.items():
        lines.append(f"{key}={val}")
    with open(ENV_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")
    ok(f".env written to {ENV_PATH}")


# ── Prompt helpers ────────────────────────────────────────────────────────────

def prompt(label: str, default: str = "") -> str:
    hint = f" [{default}]" if default else ""
    raw = input(f"  {label}{hint}: ").strip()
    return raw if raw else default


def prompt_guid(label: str, default: str = "") -> str:
    while True:
        val = prompt(label, default)
        if GUID_RE.match(val):
            return val
        err("Must be a valid GUID (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx). Try again.")


def prompt_guid_list(label: str, default: str = "") -> list[str]:
    while True:
        hint = f" [{default}]" if default else ""
        raw = input(f"  {label} (comma-separated){hint}: ").strip()
        if not raw and default:
            raw = default
        parts = [p.strip() for p in raw.split(",") if p.strip()]
        bad = [p for p in parts if not GUID_RE.match(p)]
        if parts and not bad:
            return parts
        err(f"Invalid GUIDs: {bad}. All values must be valid GUIDs.")


def prompt_int(label: str, default: int) -> int:
    while True:
        raw = input(f"  {label} [{default}]: ").strip()
        if not raw:
            return default
        try:
            val = int(raw)
            if val > 0:
                return val
            err("Must be a positive integer.")
        except ValueError:
            err("Must be a positive integer.")


def prompt_secret(existing: bool) -> str:
    """
    Returns the new secret, or '' to signal 'keep existing'.
    Never echoes the value.
    """
    hint = " (leave blank to keep existing)" if existing else ""
    val = getpass.getpass(f"  AZURE_CLIENT_SECRET{hint}: ")
    return val


# ── Azure validation ──────────────────────────────────────────────────────────

def validate_azure(tenant_id: str, client_id: str, client_secret: str,
                   subscription_ids: list[str]) -> bool:
    try:
        from azure.identity import ClientSecretCredential
        from azure.mgmt.resourcegraph import ResourceGraphClient
        from azure.mgmt.resourcegraph.models import QueryRequest

        cred = ClientSecretCredential(
            tenant_id=tenant_id,
            client_id=client_id,
            client_secret=client_secret,
        )
        client = ResourceGraphClient(cred)
        req = QueryRequest(subscriptions=subscription_ids, query="Resources | limit 1 | project id")
        result = client.resources(req)
        count = len(result.data) if result.data else 0
        ok(f"Azure connection OK — Resource Graph returned {count} row(s).")
        return True
    except Exception as exc:
        msg = str(exc)
        if "AADSTS" in msg or "authentication" in msg.lower():
            err("Authentication failed — bad client secret or client ID.")
        elif "AuthorizationFailed" in msg or "does not have authorization" in msg:
            err(
                "Auth succeeded but RBAC check failed.\n"
                "  Ensure 'Reader' + 'Cost Management Reader' are assigned on the subscription.\n"
                "  RBAC can take a few minutes to propagate — try again shortly."
            )
        else:
            err(f"Unexpected error: {msg}")
        return False


# ── Main wizard ───────────────────────────────────────────────────────────────

def main():
    print("\n=== WTS Azure Cloud Manager — Setup Wizard ===\n")

    existing = load_env(ENV_PATH)
    if existing:
        warn(f"Existing .env found — press Enter to keep each current value.\n")

    # ── Azure credentials ────────────────────────────────────────────────────
    print("── Azure credentials ──────────────────────────────────────")
    tenant_id = prompt_guid(
        "AZURE_TENANT_ID      (WTS Directory / tenant ID)",
        existing.get("AZURE_TENANT_ID", "7f8e2ae3-9032-41d0-98af-2b5294ef998b"),
    )
    client_id = prompt_guid(
        "AZURE_CLIENT_ID      (app registration client ID)",
        existing.get("AZURE_CLIENT_ID", ""),
    )

    has_existing_secret = bool(existing.get("AZURE_CLIENT_SECRET", ""))
    new_secret = prompt_secret(existing=has_existing_secret)
    if not new_secret:
        if has_existing_secret:
            client_secret = existing["AZURE_CLIENT_SECRET"]
            ok("Keeping existing client secret.")
        else:
            err("Client secret cannot be empty.")
            sys.exit(1)
    else:
        client_secret = new_secret

    subscription_ids = prompt_guid_list(
        "AZURE_SUBSCRIPTION_IDS",
        existing.get("AZURE_SUBSCRIPTION_IDS", "484960a1-4c7a-4720-9e9c-82757f797502"),
    )

    # ── Sign-in settings ─────────────────────────────────────────────────────
    print("\n── Entra sign-in settings ─────────────────────────────────")
    authority = f"https://login.microsoftonline.com/{tenant_id}"
    ok(f"AUTHORITY auto-derived: {authority}")

    auth_redirect_path = prompt(
        "AUTH_REDIRECT_PATH   (callback path registered in Entra)",
        existing.get("AUTH_REDIRECT_PATH", "/auth/callback"),
    )
    allowed_group_id = prompt(
        "ALLOWED_GROUP_ID     (optional — group object ID; blank = any tenant user)",
        existing.get("ALLOWED_GROUP_ID", ""),
    )
    if allowed_group_id and not GUID_RE.match(allowed_group_id):
        err("ALLOWED_GROUP_ID must be a valid GUID or left blank.")
        sys.exit(1)

    # ── App settings ─────────────────────────────────────────────────────────
    print("\n── App settings ───────────────────────────────────────────")
    app_port = prompt_int("APP_PORT", int(existing.get("APP_PORT", 8050)))
    sync_interval = prompt_int("SYNC_INTERVAL_MINUTES", int(existing.get("SYNC_INTERVAL_MINUTES", 60)))

    # Keep existing FLASK_SECRET_KEY — don't churn sessions on re-runs
    flask_secret = existing.get("FLASK_SECRET_KEY") or secrets.token_hex(32)
    if "FLASK_SECRET_KEY" not in existing:
        ok(f"FLASK_SECRET_KEY auto-generated ({len(flask_secret)} hex chars).")
    else:
        ok("Keeping existing FLASK_SECRET_KEY (sessions preserved).")

    # ── Validate ─────────────────────────────────────────────────────────────
    print("\nValidating credentials against Azure Resource Graph …")
    if not validate_azure(tenant_id, client_id, client_secret, subscription_ids):
        retry = input("\nValidation failed. Re-enter values? [y/N]: ").strip().lower()
        if retry == "y":
            main()
        else:
            print("Aborted — .env unchanged.")
        return

    # ── Write ─────────────────────────────────────────────────────────────────
    new_env = {
        "AZURE_TENANT_ID": tenant_id,
        "AZURE_CLIENT_ID": client_id,
        "AZURE_CLIENT_SECRET": client_secret,
        "AZURE_SUBSCRIPTION_IDS": ",".join(subscription_ids),
        "AUTHORITY": authority,
        "AUTH_REDIRECT_PATH": auth_redirect_path,
        "ALLOWED_GROUP_ID": allowed_group_id,
        "APP_PORT": str(app_port),
        "SYNC_INTERVAL_MINUTES": str(sync_interval),
        "FLASK_SECRET_KEY": flask_secret,
    }
    # Preserve any extra keys from old .env not covered above
    for k, v in existing.items():
        if k not in new_env:
            new_env[k] = v

    write_env(new_env)

    print("\nSetup complete.")
    print("  ⚠  IMPORTANT — add this redirect URI to your Entra app registration:")
    print(f"     https://<your-vm-ip>:<port>{auth_redirect_path}")
    print("     (e.g. https://192.168.1.115:8444/auth/callback)")
    print("\nNext steps:")
    print("  1. Add the redirect URI in Entra (see above)")
    print("  2. Restart the app:  systemctl --user restart wts-azure-manager")
    print("  3. Open https://192.168.1.115:8444 — you should be redirected to Microsoft login\n")
    print("  Note: the interactive browser login cannot be tested headlessly.")
    print("        Verify it by opening the portal in your browser after restart.\n")


if __name__ == "__main__":
    main()
