#!/usr/bin/env python3
"""
Interactive wizard that prompts for WTS Azure credentials, validates them
against Azure Resource Graph, then writes a .env file.
"""

import getpass
import os
import re
import secrets
import sys

GUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    re.IGNORECASE,
)
ENV_PATH = os.path.join(os.path.dirname(__file__), ".env")

GREEN = "\033[92m"
RED = "\033[91m"
YELLOW = "\033[93m"
RESET = "\033[0m"


def ok(msg):
    print(f"{GREEN}✓ {msg}{RESET}")


def err(msg):
    print(f"{RED}✗ {msg}{RESET}")


def warn(msg):
    print(f"{YELLOW}⚠ {msg}{RESET}")


def prompt_guid(label):
    while True:
        val = input(f"  {label}: ").strip()
        if GUID_RE.match(val):
            return val
        err("Must be a valid GUID (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx). Try again.")


def prompt_guid_list(label):
    while True:
        raw = input(f"  {label} (comma-separated): ").strip()
        parts = [p.strip() for p in raw.split(",") if p.strip()]
        bad = [p for p in parts if not GUID_RE.match(p)]
        if parts and not bad:
            return parts
        err(f"Invalid GUIDs: {bad}. All values must be valid GUIDs.")


def prompt_int(label, default):
    while True:
        raw = input(f"  {label} [default {default}]: ").strip()
        if not raw:
            return default
        try:
            val = int(raw)
            if val > 0:
                return val
            err("Must be a positive integer.")
        except ValueError:
            err("Must be a positive integer.")


def validate_azure(tenant_id, client_id, client_secret, subscription_ids):
    """Attempt a trivial Resource Graph query to prove credentials work."""
    try:
        from azure.identity import ClientSecretCredential
        from azure.mgmt.resourcegraph import ResourceGraphClient
        from azure.mgmt.resourcegraph.models import QueryRequest

        cred = ClientSecretCredential(
            tenant_id=tenant_id,
            client_id=client_id,
            client_secret=client_secret,
        )
        client = ResourceGraphClient(cred)
        req = QueryRequest(
            subscriptions=subscription_ids,
            query="Resources | limit 1 | project id",
        )
        result = client.resources(req)
        count = len(result.data) if result.data else 0
        ok(f"Azure connection successful — Resource Graph returned {count} row(s).")
        return True
    except Exception as exc:
        msg = str(exc)
        if "AADSTS" in msg or "authentication" in msg.lower():
            err("Authentication failed — check AZURE_TENANT_ID / AZURE_CLIENT_ID / AZURE_CLIENT_SECRET.")
        elif "AuthorizationFailed" in msg or "does not have authorization" in msg:
            err(
                "Auth succeeded but RBAC check failed.\n"
                "  The service principal needs 'Reader' + 'Cost Management Reader'\n"
                f"  on subscriptions: {subscription_ids}\n"
                "  RBAC assignments can take a few minutes to propagate — try again shortly."
            )
        else:
            err(f"Unexpected error: {msg}")
        return False


def write_env(values):
    lines = [
        "# WTS Azure Cloud Manager — generated by setup_env.py",
        f"AZURE_TENANT_ID={values['tenant_id']}",
        f"AZURE_CLIENT_ID={values['client_id']}",
        f"AZURE_CLIENT_SECRET={values['client_secret']}",
        f"AZURE_SUBSCRIPTION_IDS={','.join(values['subscription_ids'])}",
        f"APP_PORT={values['app_port']}",
        f"SYNC_INTERVAL_MINUTES={values['sync_interval']}",
        f"FLASK_SECRET_KEY={values['flask_secret']}",
    ]
    with open(ENV_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")
    ok(f".env written to {ENV_PATH}")


def main():
    print("\n=== WTS Azure Cloud Manager — Setup Wizard ===\n")

    if os.path.exists(ENV_PATH):
        warn(f".env already exists at {ENV_PATH}")
        confirm = input("  Overwrite? [y/N]: ").strip().lower()
        if confirm != "y":
            print("Aborted — existing .env unchanged.")
            sys.exit(0)

    print("Enter WTS Azure credentials (tenant ID, client ID, secret, subscription IDs).\n")

    tenant_id = prompt_guid("AZURE_TENANT_ID      (WTS Directory / tenant ID)")
    client_id = prompt_guid("AZURE_CLIENT_ID      (WTS-Azure-Manager app / client ID)")
    client_secret = getpass.getpass("  AZURE_CLIENT_SECRET  (input hidden): ")
    if not client_secret:
        err("Client secret cannot be empty.")
        sys.exit(1)
    subscription_ids = prompt_guid_list(
        "AZURE_SUBSCRIPTION_IDS (WTS subscription GUIDs)"
    )
    app_port = prompt_int("APP_PORT", 8050)
    sync_interval = prompt_int("SYNC_INTERVAL_MINUTES", 60)

    flask_secret = secrets.token_hex(32)
    ok(f"FLASK_SECRET_KEY auto-generated ({len(flask_secret)} hex chars).")

    print("\nValidating credentials against Azure Resource Graph …")
    success = validate_azure(tenant_id, client_id, client_secret, subscription_ids)

    if not success:
        retry = input("\nCredentials failed. Re-enter values? [y/N]: ").strip().lower()
        if retry == "y":
            main()
        else:
            print("Aborted — no .env written.")
        return

    write_env(
        {
            "tenant_id": tenant_id,
            "client_id": client_id,
            "client_secret": client_secret,
            "subscription_ids": subscription_ids,
            "app_port": app_port,
            "sync_interval": sync_interval,
            "flask_secret": flask_secret,
        }
    )
    print("\nSetup complete. Next steps:")
    print("  1. python -m sync.sync_job          # run first sync")
    print("  2. python app.py                    # dev server")
    print("  3. sudo systemctl enable --now wts-azure-manager   # prod\n")


if __name__ == "__main__":
    main()
